### ISSUE TITLE
[new feature] Local sandboxes are unable to resolve external names

### ISSUE THREAD

**Issue by gamino-brex** [signadot/community#43]
**New feature or functionality**

The current Signadot's local sandbox/connection infrastructure does not support hitting `externalName` services. This limitation is causing issues with users being unable to access AWS services (e.g. Redis).

The problem is critical as it is preventing any workload that relies on external services from being able to run under our local tooling.

**Comment by scott-cotton** [comment]
This limitation was deliberate because our `signadot local connect` uses the IP addresses in the cluster, and we didn't like the idea of a 3rd party changing DNS records causing routing changes on people's workstation.

But it makes things quite hard to use if one needs to resolve those services.  Similar reasoning applies to headless services.

We have decided to address this by adding a layer of IP mapping over a per-local-machine configurable IP address block, so that the local workstation can set up routing once and not be affected by potentially volatile in-cluster DNS or routing.

We should be to support these soon, and part of that work is available [here](https://github.com/signadot/cli/pull/103).

**Comment by scott-cotton** [comment]
This has been released, so closing.  Please feel free to re-open if needed.
